project:
  name: word-sense-disambiguation
  syncFilters:
    - exclude:
        - .idea/*
        - .git/*
        - '*/__pycache__/*'
        - data/*

container:
  projectDir: /workspace/project
  file: docker/Dockerfile.spotty
  ports: [6006, 8888]
  volumeMounts:
    - name: workspace
      mountPath: /workspace


instances:
  - name: i1
    provider: aws
    parameters:
      region: us-east-2
      instanceType: p2.xlarge
      dockerDataRoot: /docker
      volumes:
        - name: workspace
          parameters:
            size: 50
            deletionPolicy: retain
        - name: docker
          parameters:
            size: 10
            mountDir: /docker
            deletionPolicy: retain

scripts:
  preprocess: |
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1mW70p3xEm_H-w0KMuqsTenP7IUl9P9Lr' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1mW70p3xEm_H-w0KMuqsTenP7IUl9P9Lr" -O 2m_cosine_distances_max.csv && rm -rf /tmp/cookies.txt
  train: |
    python fine_tune_mult_neg_rank_loss.py
  tensorboard: |
    tensorboard --logdir /workspace/project/logs-Tacotron-2
  jupyter: |
    jupyter notebook --allow-root --ip 0.0.0.0 --notebook-dir=/workspace/project